language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libicu-dev

before_script:
    - ./travis/compile-php.sh
    - ./travis/compile-ext.sh

script:
    - ./travis/run-tests.sh

